
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:      
      - .ivy2
      - .m2
    volumes:
      - /tmp/cache:/cache
  api:
    image: bigtruedata/sbt:0.13.15-2.11.8
    commands:
      - mkdir -p ~/.sbt/0.13
      - cp global.sbt ~/.sbt/0.13
      - sbt -Dsbt.ivy.home=./.ivy2 clean test publishM2
    secrets: [ artifactory_host, artifactory_url, artifactory_username, artifactory_password ]
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - .ivy2
      - .m2
    volumes:
      - /tmp/cache:/cache
  artifactory:
    image: athieriot/drone-artifactory
    environment:
      - DRONE_VERSION=0.8
    group_id: org.dcs
    artifact_id: org.dcs.remote
    version: 0.5.0-SNAPSHOT
    pom: target/org.dcs.api-0.5.0-SNAPSHOT.pom
    files:
      - target/*.jar
    force_upload: true
    secrets: [ artifactory_url, artifactory_username, artifactory_password ]
    when:
      branch: master
      status: [ success ]
  slack:
    image: plugins/slack
    channel: builds
    secrets: [ slack_webhook ]
    when:
      branch: master
      status: [ success, failure ]


